apply plugin: 'com.android.application'

android {
    compileSdk 36
    buildToolsVersion "36.0.0"

    namespace "com.zipflash.mrp"

    defaultConfig {
        applicationId "com.zipflash.mrp"
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName "1.0.0.9"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            buildConfigField "boolean", "USE_SHIZUKU_PROVIDER", "true"
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "boolean", "USE_SHIZUKU_PROVIDER", "true"
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'dev.rikka.shizuku:api:12.2.0'
    implementation 'dev.rikka.shizuku:provider:12.2.0'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
